# Gruvbox Dark colorscheme for mango

rootcolor=0x282828ff
bordercolor=0x504945ff
dropcolor=0xb8bb2655
splitcolor=0xfe8019ff
focuscolor=0x83a598ff
maximizescreencolor=0xb8bb26ff
urgentcolor=0xfb4934ff
scratchpadcolor=0x8ec07cff
globalcolor=0xd3869bff
overlaycolor=0x689d6aff
