# Tokyo Night colorscheme for mango
# (cores extraídas do config.conf original)

rootcolor=0x1a1b26ff
bordercolor=0x414868ff
dropcolor=0x9ece6a55
splitcolor=0xff9e64ff
focuscolor=0x7aa2f7ff
maximizescreencolor=0x9ece6aff
urgentcolor=0xf7768eff
scratchpadcolor=0x7dcfffff
globalcolor=0xbb9af7ff
overlaycolor=0x73dacaff
