db_file            "~/.config/mpd/mpd.db"
music_directory    "~/music"
auto_update        "yes"
playlist_directory "~/.config/mpd/playlists"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"
#bind_to_address    "0.0.0.0"

audio_output {
  type    "pipewire"
  name    "PipeWire Sound Server"
}

audio_output {
  type    "fifo"
  name    "FIFO"
  path    "/tmp/mpd.fifo"
  format  "44100:16:2"
}
